### ISSUE TITLE
Fail with 18S data and vsearch algorithm

### ISSUE THREAD

**Issue by hariszaf** [hariszaf/pema#22]
Christina has found a bug when using 18S data. 
@cpavloud Could you please describe it?

**Comment by cpavloud** [comment]
I wanted to run 18S data using the current version (pema v.2.1.3) and with the vsearch algorithm. 
So, at the "GENE -  dependent parameters" I wrote

`gene	gene_18S`

However, an error was coming up (which I will find and add here). 

But then I tricked the parameters and instead of 18S, I wrote

`gene	gene_16S`

And everything worked fine.

**Comment by hariszaf** [comment]
The issue has been resolved simultaneously with the #24 issue.

**Comment by hariszaf** [comment]
In addition, a [`sannity_check`](https://github.com/hariszaf/pema/tree/fix_coi_assignment/pema_docker_image/sanity_check) folder is now available.
Input data and parameters files support cross checking each and every marker gene and software combination.
