### ISSUE TITLE
alternative database for COI marker gene

### ISSUE THREAD

**Issue by hariszaf** [hariszaf/pema#41]
A new db mostly for metazoan was recently published: 
[repo](https://github.com/bachob5/MetaCOXI)
[publication](https://academic.oup.com/database/article/doi/10.1093/database/baab084/6521297) 

consider training crest or rdp with that and integrate it the pema workfow. 

@cpavloud check and share your thougts! :sweat_smile:

**Comment by cpavloud** [comment]
It would be great if in the publication they did some kind of comparison with other databases. 
I.e. if we have a mock community and we classify it based on e.g. MIDORI and MetaCOXI, which are the differences, which one is "better" etc. 
Since they haven't done something like that, I wouldn't prioritize adding MetaCOXI in PEMA.

**Comment by hariszaf** [comment]
Ok nice.
